max_width = 100
blank_lines_lower_bound = 0
blank_lines_upper_bound = 4
comment_width = 80
wrap_comments = true
normalize_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 70
format_strings = true
hard_tabs = true
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
use_field_init_shorthand = true
